from enum import Enum


class RegionCode(Enum):
    """
    ASCII codes for known regions (e.g. RMC[E]01, where E is `NTSC`)
    """
    ALL_REGIONS = "A"
    WIIWARE_B = "B"
    CHINA_EMU = "C"
    DVDX_V7 = "C"
    GERMAN = "D"
    NTSC = "E"
    FRENCH = "F"
    ITALIAN = "I"
    HOMEBREW = "I"
    JAPAN = "J"
    KOREA = "K"
    JAPAN_EU = "L"
    USA_EU = "M"
    JAPAN_USA = "N"
    PAL = "P"
    KOREA_JP = "Q"
    SPANISH = "S"
    KOREA_USA = "T"
    WIIWARE_U = "U"
    TAIWAN = "W"
    WIIWARE_X = "X"
    DVDX_OLD = "X"
    HOMEBREW_OLD = "X"


class SystemCode(Enum):
    """
    ASCII codes for known systems (e.g. [R]MCE01, where R is `WII_DISC_OLD`)
    """
    COMMODORE_64 = "C"
    DEMO_DISC = "D"
    ARCADE = "E"
    NEOGEO = "E"
    NES = "F"
    GAMECUBE_DISC = "G"
    GENERAL_CHANNEL = "H"
    SNES = "J"
    MASTER_SYSTEM = "L"
    GENESIS = "M"
    N64 = "N"
    PROMO_DISC = "P"
    TURBOGRAFX = "P"
    TURBOGRAFX_CD = "Q"
    WII_DISC_OLD = "R"
    WII_DISC_NEW = "S"
    WIIWARE = "W"
    WIIWARE_DEMO = "X"
    MSX = "X"
